name: Maven CI/CD
run-name: ${{ github.actor }} started Maven workflow

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'

      - name: Build project with Maven
        run: mvn -B package --file pom.xml